# Generated by Django 3.0.5 on 2020-05-20 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
